// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KLToolWindows
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidKLToolWindowsPackageString = "5d0eac76-90b1-45ab-814b-b2e7a1ca7379";
        public static Guid guidKLToolWindowsPackage = new Guid(guidKLToolWindowsPackageString);

        public const string guidKLToolWindowsPackageCmdSetString = "7927f498-26bf-4f2e-8d37-458902b754e9";
        public static Guid guidKLToolWindowsPackageCmdSet = new Guid(guidKLToolWindowsPackageCmdSetString);

        public const string guidImagesString = "78fdef1e-7a1c-4565-9dad-4aeb0190d343";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int KLToolWindowsMenuGroup = 0x1020;
        public const int KLToolWindowsMenu = 0x1021;
        public const int WpfToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPic3 = 0x0003;
        public const int bmpPic4 = 0x0004;
        public const int bmpPic5 = 0x0005;
        public const int bmpPic6 = 0x0006;
    }
}